# IMPORTED LIB

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import joblib
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from tqdm import tqdm
from spotipy.oauth2 import SpotifyOAuth

# LOADING CSV FILES

In [2]:

songs_df = pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\archive\\songs_with_audio_feature.csv')  # Song data
artists_df = pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\archive\\artists.csv')  # Artist data
albums_df = pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\archive\\albums.csv')  # Album data

# SONGS CSVS ANALYSIS

In [3]:
songs_df.head()

,track_id,track_name,album_id,artist_ids,artist_names,valence,year,acousticness,danceability,duration_ms,...,explicit,instrumentalness,key,liveness,loudness,mode,popularity,release_date,speechiness,tempo
0,4BJqT0PrAfrxzMOxytFOIz,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",6UKhQXIboybG7JPka28bZR,"['0Kekt6CKSo0m5mivKcoH51', '4qFQgEF1rg6a9WvJM0...","['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.0594,1921,0.982,0.279,831667,...,0,0.878000,10,0.665,-20.096,1,4,1921,0.0366,80.954
1,7xPhfUan2yNtyFG0cUWkt8,Clancy Lowered the Boom,4LePw1NceheT4selvgH0cE,['0y60qXGlDixlFJcjUU6pwY'],['Dennis Day'],0.9630,1921,0.732,0.819,180533,...,0,0.000000,7,0.160,-12.441,1,5,1921,0.4150,60.936
2,1o6I8BglA6ylDMrIELygv1,Gati Bali,3kjFZyMpkcTARMXuLrpipj,['7u5sCPrTVbLMZMlogVRZc0'],['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.0394,1921,0.961,0.328,500062,...,0,0.913000,3,0.101,-14.850,1,5,1921,0.0339,110.339
3,3ftBPsC5vPBKxYSee08FDH,Danny Boy,4LePw1NceheT4selvgH0cE,['1gY7W6RY3EHWRWSv9Dhjqa'],['Frank Parker'],0.1650,1921,0.967,0.275,210000,...,0,0.000028,5,0.381,-9.316,1,3,1921,0.0354,100.109
4,4d6HGyGT8e121BsdKmw9v6,When Irish Eyes Are Smiling,4LePw1NceheT4selvgH0cE,['08egOYfLsuZvkG0jFN7nUj'],['Phil Regan'],0.2530,1921,0.957,0.418,166693,...,0,0.000002,3,0.229,-10.096,1,2,1921,0.0380,101.665

In [4]:
songs_df.columns

Index(['track_id', 'track_name', 'album_id', 'artist_ids', 'artist_names',
       'valence', 'year', 'acousticness', 'danceability', 'duration_ms',
       'energy', 'explicit', 'instrumentalness', 'key', 'liveness', 'loudness',
       'mode', 'popularity', 'release_date', 'speechiness', 'tempo'],
      dtype='object')

In [5]:
songs_df['artist_ids'].apply(type).value_counts()

artist_ids
<class 'str'>    35200
Name: count, dtype: int64

In [6]:
songs_df['artist_names']

0        ['Sergei Rachmaninoff', 'James Levine', 'Berli...
1                                           ['Dennis Day']
2        ['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...
3                                         ['Frank Parker']
4                                           ['Phil Regan']
                               ...
35195                                      ['Evanescence']
35196                                  ['Alberto Pedraza']
35197                                  ['Marques Houston']
35198                                      ['Linkin Park']
35199                                     ['Jack Johnson']
Name: artist_names, Length: 35200, dtype: object

In [7]:
songs_df.shape

(35200, 21)

In [7]:
songs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35200 entries, 0 to 35199
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   track_id          35200 non-null  object
 1   track_name        35200 non-null  object
 2   album_id          35200 non-null  object
 3   artist_ids        35200 non-null  object
 4   artist_names      35200 non-null  object
 5   valence           35200 non-null  float64
 6   year              35200 non-null  int64
 7   acousticness      35200 non-null  float64
 8   danceability      35200 non-null  float64
 9   duration_ms       35200 non-null  int64
 10  energy            35200 non-null  float64
 11  explicit          35200 non-null  int64
 12  instrumentalness  35200 non-null  float64
 13  key               35200 non-null  int64
 14  liveness          35200 non-null  float64
 15  loudness          35200 non-null  float64
 16  mode              35200 non-null  int64
 17  popularity        35200 non-null  int64
 18  release_date      35200 non-null  object
 19  speechiness       35200 non-null  float64
 20  tempo             35200 non-null  float64
dtypes: float64(9), int64(6), object(6)
memory usage: 5.6+ MB

In [ ]:
#check for null values 

print(songs_df.isnull())

# Step 3: Get the count of nulls in each column
print(songs_df.isnull().sum())

       track_id  track_name  album_id  artist_ids  artist_names  valence  \
0         False       False     False       False         False    False
1         False       False     False       False         False    False
2         False       False     False       False         False    False
3         False       False     False       False         False    False
4         False       False     False       False         False    False
...         ...         ...       ...         ...           ...      ...
35195     False       False     False       False         False    False
35196     False       False     False       False         False    False
35197     False       False     False       False         False    False
35198     False       False     False       False         False    False
35199     False       False     False       False         False    False

        year  acousticness  danceability  duration_ms  ...  explicit  \
0      False         False         False        False  ...     False
1      False         False         False        False  ...     False
2      False         False         False        False  ...     False
3      False         False         False        False  ...     False
4      False         False         False        False  ...     False
...      ...           ...           ...          ...  ...       ...
35195  False         False         False        False  ...     False
35196  False         False         False        False  ...     False
35197  False         False         False        False  ...     False
35198  False         False         False        False  ...     False
35199  False         False         False        False  ...     False

       instrumentalness    key  liveness  loudness   mode  popularity  \
0                 False  False     False     False  False       False
1                 False  False     False     False  False       False
2                 False  False     False     False  False       False
3                 False  False     False     False  False       False
4                 False  False     False     False  False       False
...                 ...    ...       ...       ...    ...         ...
35195             False  False     False     False  False       False
35196             False  False     False     False  False       False
35197             False  False     False     False  False       False
35198             False  False     False     False  False       False
35199             False  False     False     False  False       False

       release_date  speechiness  tempo
0             False        False  False
1             False        False  False
2             False        False  False
3             False        False  False
4             False        False  False
...             ...          ...    ...
35195         False        False  False
35196         False        False  False
35197         False        False  False
35198         False        False  False
35199         False        False  False

[35200 rows x 21 columns]
track_id            0
track_name          0
album_id            0
artist_ids          0
artist_names        0
valence             0
year                0
acousticness        0
danceability        0
duration_ms         0
energy              0
explicit            0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
popularity          0
release_date        0
speechiness         0
tempo               0
dtype: int64

# Artists csvs

In [8]:
artists_df

,artist_id,artist_name,genres,followers,popularity
0,0Kekt6CKSo0m5mivKcoH51,Sergei Rachmaninoff,"['classical', 'post-romantic era', 'russian ro...",753124,65
1,4qFQgEF1rg6a9WvJM0MQIa,James Levine,"['classical performance', 'opera']",9206,53
2,6uRJnvQ3f8whVnmeoecv5Z,Berliner Philharmoniker,"['classical', 'classical performance', 'german...",223580,73
3,2DG9aIMzcln3w7SIVGGnmg,Arcadi Volodos,"['classical piano', 'russian classical piano']",17186,47
4,0y60qXGlDixlFJcjUU6pwY,Dennis Day,[],684,7
...,...,...,...,...,...
14634,1eNJZfAHoq5zu1sUukbhAe,Carlos Lafuente,['orquesta tipica'],84,3
14635,0mhWWtpVIh60Ney5hbeR93,Orquesta Víctor Popular,[],0,0
14636,01eq7T47JHOrYY0nfpdDYT,Serafim Gerotheodorou,[],2,0
14637,0nRShN4m4GvQv1O4igorb6,Ernesto Fama,['vintage tango'],1363,19
14638,4klba9nOUmD5XsUVjlAFM5,Pello Revolvers,[],58,0

In [9]:
artists_df.columns

Index(['artist_id', 'artist_name', 'genres', 'followers', 'popularity'], dtype='object')

In [81]:
artists_df['artist_id']

0        0Kekt6CKSo0m5mivKcoH51
1        4qFQgEF1rg6a9WvJM0MQIa
2        6uRJnvQ3f8whVnmeoecv5Z
3        2DG9aIMzcln3w7SIVGGnmg
4        0y60qXGlDixlFJcjUU6pwY
                  ...
14634    1eNJZfAHoq5zu1sUukbhAe
14635    0mhWWtpVIh60Ney5hbeR93
14636    01eq7T47JHOrYY0nfpdDYT
14637    0nRShN4m4GvQv1O4igorb6
14638    4klba9nOUmD5XsUVjlAFM5
Name: artist_id, Length: 14639, dtype: object

In [13]:
artists_df.shape

(14639, 5)

In [14]:
artists_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14639 entries, 0 to 14638
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   artist_id    14639 non-null  object
 1   artist_name  14639 non-null  object
 2   genres       14639 non-null  object
 3   followers    14639 non-null  int64
 4   popularity   14639 non-null  int64
dtypes: int64(2), object(3)
memory usage: 572.0+ KB

In [15]:
artists_df.describe()

          followers    popularity
count  1.463900e+04  14639.000000
mean   4.038699e+06     54.615479
std    1.138902e+07     23.378139
min    0.000000e+00      0.000000
25%    3.526900e+04     45.000000
50%    6.345500e+05     60.000000
75%    2.978840e+06     71.000000
max    1.235448e+08    100.000000

In [16]:
print(artists_df.isnull())

# Step 3: Get the count of nulls in each column
print(artists_df.isnull().sum())

       artist_id  artist_name  genres  followers  popularity
0          False        False   False      False       False
1          False        False   False      False       False
2          False        False   False      False       False
3          False        False   False      False       False
4          False        False   False      False       False
...          ...          ...     ...        ...         ...
14634      False        False   False      False       False
14635      False        False   False      False       False
14636      False        False   False      False       False
14637      False        False   False      False       False
14638      False        False   False      False       False

[14639 rows x 5 columns]
artist_id      0
artist_name    0
genres         0
followers      0
popularity     0
dtype: int64

# ALBUMS CSVS

In [17]:
albums_df

,album_id,album_name,release_date,total_tracks,album_type,album_cover_64x64,album_cover_640x640
0,6UKhQXIboybG7JPka28bZR,The Rachmaninoff Collection,2006-06-27,11,compilation,https://i.scdn.co/image/ab67616d000048515a7c6e...,https://i.scdn.co/image/ab67616d000048515a7c6e...
1,4LePw1NceheT4selvgH0cE,Original Irish Tenors: The Legendary Voices Of...,2006-02-20,21,compilation,https://i.scdn.co/image/ab67616d00004851ab0547...,https://i.scdn.co/image/ab67616d00004851ab0547...
2,3kjFZyMpkcTARMXuLrpipj,Gendhing Gati,1921,17,album,https://i.scdn.co/image/ab67616d000048512f1bfe...,https://i.scdn.co/image/ab67616d000048512f1bfe...
3,59DmiBZi588gd8yklEgIlS,Rachmaninoff: Greatest Hits,2009-03-27,11,compilation,https://i.scdn.co/image/ab67616d0000485125dab7...,https://i.scdn.co/image/ab67616d0000485125dab7...
4,4PSwdsOtNdinZE8mijH4E6,"Colección Completa, Vol. 2 (Remasterizado)",1921-03-20,21,album,https://i.scdn.co/image/ab67616d00004851fc669e...,https://i.scdn.co/image/ab67616d00004851fc669e...
...,...,...,...,...,...,...,...
11663,5nk0pXd9S0igSZGjudpB4p,"Música Boliviana, 78 Rpm Recordings, Vol. 1 (1...",1930-01-01,26,compilation,https://i.scdn.co/image/ab67616d000048510a30a5...,https://i.scdn.co/image/ab67616d0000b2730a30a5...
11664,6d48OUlyh79FQDhbwWgKxF,"Colección Completa, Vol. 53 (Remasterizado)",1930-12-05,17,album,https://i.scdn.co/image/ab67616d00004851a88f55...,https://i.scdn.co/image/ab67616d0000b273a88f55...
11665,47dahsZ5pIBo8mNH0qeL0C,Borg Mesch - EP,1930-04-01,5,single,https://i.scdn.co/image/ab67616d000048514e542e...,https://i.scdn.co/image/ab67616d0000b2734e542e...
11666,2jfKd4aGugEQmaPzXZ5L0d,"Colección Completa, Vol. 52 (Remasterizado)",1930-12-03,18,album,https://i.scdn.co/image/ab67616d00004851fe9c4e...,https://i.scdn.co/image/ab67616d0000b273fe9c4e...
11667,1za67i3IBsXiMcQsSAyrwQ,"Ta Rempetika Tou Grammofonou, Νο. 5",1930-01-01,21,compilation,https://i.scdn.co/image/ab67616d000048518de083...,https://i.scdn.co/image/ab67616d0000b2738de083...

In [18]:
albums_df.columns

Index(['album_id', 'album_name', 'release_date', 'total_tracks', 'album_type',
       'album_cover_64x64', 'album_cover_640x640'],
      dtype='object')

In [19]:
albums_df.shape

(11668, 7)

In [20]:
albums_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11668 entries, 0 to 11667
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   album_id             11668 non-null  object
 1   album_name           11668 non-null  object
 2   release_date         11668 non-null  object
 3   total_tracks         11668 non-null  int64
 4   album_type           11668 non-null  object
 5   album_cover_64x64    11668 non-null  object
 6   album_cover_640x640  11668 non-null  object
dtypes: int64(1), object(6)
memory usage: 638.2+ KB

In [21]:
print(albums_df.isnull())

# Step 3: Get the count of nulls in each column
print(albums_df.isnull().sum())

       album_id  album_name  release_date  total_tracks  album_type  \
0         False       False         False         False       False
1         False       False         False         False       False
2         False       False         False         False       False
3         False       False         False         False       False
4         False       False         False         False       False
...         ...         ...           ...           ...         ...
11663     False       False         False         False       False
11664     False       False         False         False       False
11665     False       False         False         False       False
11666     False       False         False         False       False
11667     False       False         False         False       False

       album_cover_64x64  album_cover_640x640
0                  False                False
1                  False                False
2                  False                False
3                  False                False
4                  False                False
...                  ...                  ...
11663              False                False
11664              False                False
11665              False                False
11666              False                False
11667              False                False

[11668 rows x 7 columns]
album_id               0
album_name             0
release_date           0
total_tracks           0
album_type             0
album_cover_64x64      0
album_cover_640x640    0
dtype: int64

# PROCESSED SONGS  DATA SETS 
  1) NO NULL VALUES 
  2) ADD MOOD COLUMNS

In [14]:
# Import libraries
import pandas as pd  # for data manipulation
import numpy as np   # for numerical operations

# Load datasets
songs_df = pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\archive\\songs_with_audio_feature.csv')
artists_df = pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\archive\\artists.csv')
albums_df = pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\archive\\albums.csv')

# Convert artist_ids from string to list
songs_df['artist_ids'] = songs_df['artist_ids'].apply(eval)

# Aggregate genres from all artists involved in a song
def aggregate_genres(group):
    genres = artists_df[artists_df['artist_id'].isin(group['artist_ids'])]['genres'].tolist()
    flat_list = [g for sublist in [eval(g) if isinstance(g, str) else g for g in genres] for g in sublist]
    return ', '.join(set(flat_list)) if flat_list else 'Unknown'

# Group by track_id to avoid duplicates and keep relevant audio features and metadata
songs_df = songs_df.groupby('track_id').agg({
    'track_name': 'first',
    'artist_names': 'first',
    'artist_ids': 'first',
    'valence': 'first',
    'danceability': 'first',
    'energy': 'first',
    'album_id': 'first'  #  merging with album info
}).reset_index()

# Add genre info to each track
songs_df['genres'] = songs_df.apply(aggregate_genres, axis=1)

# Assign mood labels based on valence (positiveness of a track)
def assign_mood(valence):
    if valence > 0.6:
        return 'Upbeat'
    elif valence < 0.4:
        return 'Sad'
    else:
        return 'Neutral'

songs_df['mood'] = songs_df['valence'].apply(assign_mood)

# Merge with album data to get album name, release date, and cover image
songs_df = pd.merge(
    songs_df,
    albums_df[['album_id', 'album_name', 'release_date', 'album_cover_640x640']],
    on='album_id',
    how='left'
)

# Final dataset structure
final_df = songs_df[[
    'track_id', 'track_name', 'artist_names', 'genres',
    'valence', 'danceability', 'energy', 'mood',
    'album_name', 'release_date', 'album_cover_640x640'
]]

# Save the cleaned and enriched dataset
final_df.to_csv('D:\\snap_tune_final\\snap_tune_project\\proceesed_songs\\processed_songs_final.csv', index=False)

# Output confirmation
print(f" Processed dataset shape: {final_df.shape}")
print(final_df.head())

 Processed dataset shape: (56580, 11)
                 track_id                            track_name  \
0  001ZmOPuWEW5czwun7nkha                Would You? (End Title)
1  001ZmOPuWEW5czwun7nkha                Would You? (End Title)
2  001ZmOPuWEW5czwun7nkha                Would You? (End Title)
3  003FTlCpBTM4eSqYSWPv4H                          Swing, Swing
4  003JzPprzThp8SHUctgXnn  Willow Weep For Me - Remastered 1998

                    artist_names  \
0  ['Gene Kelly', 'Betty Noyes']
1  ['Gene Kelly', 'Betty Noyes']
2  ['Gene Kelly', 'Betty Noyes']
3   ['The All-American Rejects']
4            ['Thelonious Monk']

                                              genres  valence  danceability  \
0    adult standards, movie tunes, vintage hollywood    0.162         0.160
1    adult standards, movie tunes, vintage hollywood    0.162         0.160
2    adult standards, movie tunes, vintage hollywood    0.162         0.160
3  modern rock, alternative metal, pop rock, pop ...    0.318         0.553
4  jazz trio, contemporary post-bop, jazz, jazz p...    0.298         0.461

   energy mood                                         album_name  \
0   0.120  Sad  Singin' in the Rain (Original Motion Picture S...
1   0.120  Sad  Singin' in the Rain (Original Motion Picture S...
2   0.120  Sad  Singin' in the Rain (Original Motion Picture S...
3   0.717  Sad                           The All-American Rejects
4   0.454  Sad   Genius Of Modern Music (Vol.2, Expanded Edition)

  release_date                                album_cover_640x640
0   1952-04-11  https://i.scdn.co/image/ab67616d00004851701dfe...
1   1952-04-11  https://i.scdn.co/image/ab67616d00004851701dfe...
2   1952-04-11  https://i.scdn.co/image/ab67616d00004851701dfe...
3   2002-10-15  https://i.scdn.co/image/ab67616d0000b273eba2ac...
4         1952  https://i.scdn.co/image/ab67616d00004851a36b4e...

In [15]:

# Load processed dataset
processed_songs_df = pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\proceesed_songs\\processed_songs_final.csv')

In [16]:
processed_songs_df.shape

(56580, 11)

In [17]:
# Check for duplicate songs (based on track_id)
duplicate_tracks = processed_songs_df[processed_songs_df.duplicated(subset=['track_id'], keep=False)]
print(f"Number of rows with duplicate track_id: {len(duplicate_tracks)}")
print(f"Unique track_id count: {processed_songs_df['track_id'].nunique()}")

Number of rows with duplicate track_id: 36914
Unique track_id count: 35200

# CHECKED FOR DUPLICATES

In [18]:


# Load processed dataset
processed_songs_df = pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\proceesed_songs\\processed_songs_final.csv')

# Check for duplicate songs (based on track_id)
duplicate_tracks = processed_songs_df[processed_songs_df.duplicated(subset=['track_id'], keep=False)]
print(f"Number of rows with duplicate track_id: {len(duplicate_tracks)}")
print(f"Unique track_id count: {processed_songs_df['track_id'].nunique()}")

# Example of duplicates (only if duplicates exist)
if len(duplicate_tracks) > 0:
    print("\nSample duplicates:")
    print(duplicate_tracks[['track_id', 'track_name', 'artist_names', 'genres']].head(10))
else:
    print("\nNo duplicates found.")

Number of rows with duplicate track_id: 36914
Unique track_id count: 35200

Sample duplicates:
                  track_id                               track_name  \
0   001ZmOPuWEW5czwun7nkha                   Would You? (End Title)
1   001ZmOPuWEW5czwun7nkha                   Would You? (End Title)
2   001ZmOPuWEW5czwun7nkha                   Would You? (End Title)
4   003JzPprzThp8SHUctgXnn     Willow Weep For Me - Remastered 1998
5   003JzPprzThp8SHUctgXnn     Willow Weep For Me - Remastered 1998
6   003vvx7Niy0yvhvHt4a68B                           Mr. Brightside
7   003vvx7Niy0yvhvHt4a68B                           Mr. Brightside
9   004TG0nRHejwSKisvwTcAB               The Garden of Gethesemanie
10  004TG0nRHejwSKisvwTcAB               The Garden of Gethesemanie
14  006fbuXS6rRAWlUEaklCmt  Kapitel 297 - Der Page und die Herzogin

                           artist_names  \
0         ['Gene Kelly', 'Betty Noyes']
1         ['Gene Kelly', 'Betty Noyes']
2         ['Gene Kelly', 'Betty Noyes']
4                   ['Thelonious Monk']
5                   ['Thelonious Monk']
6                       ['The Killers']
7                       ['The Killers']
9         ['Emahoy Tsege Mariam Gebru']
10        ['Emahoy Tsege Mariam Gebru']
14  ['Georgette Heyer', 'Irina Salkow']

                                               genres
0     adult standards, movie tunes, vintage hollywood
1     adult standards, movie tunes, vintage hollywood
2     adult standards, movie tunes, vintage hollywood
4   jazz trio, contemporary post-bop, jazz, jazz p...
5   jazz trio, contemporary post-bop, jazz, jazz p...
6   permanent wave, modern rock, alternative rock,...
7   permanent wave, modern rock, alternative rock,...
9                           impressionism, ethio-jazz
10                          impressionism, ethio-jazz
14                                            Unknown

# DROP DUPLICATES AND KEEPING THE FIRST OCCURENCES

In [19]:
# Drop duplicates based on track_id and keep the first occurrence
deduped_df = processed_songs_df.drop_duplicates(subset='track_id', keep='first')

# Save cleaned version
deduped_df.to_csv('D:\\snap_tune_final\\snap_tune_project\\proceesed_songs\\processed_songs_deduped.csv', index=False)

print(f" Deduplicated dataset shape: {deduped_df.shape}")

 Deduplicated dataset shape: (35200, 11)

In [20]:

# Check for duplicate songs (based on track_id)
duplicate_tracks = deduped_df[deduped_df.duplicated(subset=['track_id'], keep=False)]
print(f"Number of rows with duplicate track_id: {len(duplicate_tracks)}")
print(f"Unique track_id count: {deduped_df['track_id'].nunique()}")

# Example of duplicates (only if duplicates exist)
if len(duplicate_tracks) > 0:
    print("\nSample duplicates:")
    print(duplicate_tracks[['track_id', 'track_name', 'artist_names', 'genres']].head(10))
else:
    print("\nNo duplicates found.")

Number of rows with duplicate track_id: 0
Unique track_id count: 35200

No duplicates found.

In [21]:
# Check for duplicates on track_id
duplicates_by_id = deduped_df[deduped_df['track_id'].duplicated()]
print("Duplicates by track_id:", len(duplicates_by_id))

# Check for duplicates on track_name + artist_names
duplicates_by_name_artist = deduped_df[deduped_df[['track_name', 'artist_names']].duplicated()]
print("Duplicates by name and artist:", len(duplicates_by_name_artist))

Duplicates by track_id: 0
Duplicates by name and artist: 1966

In [22]:
duplicates_by_name_artist = deduped_df[deduped_df.duplicated(subset=['track_name', 'artist_names'], keep=False)]
print(duplicates_by_name_artist[['track_name', 'artist_names', 'valence', 'energy', 'album_name']].head(10))

                                            track_name  \
6                                       Mr. Brightside
27                                     Tight Like This
31                                     Ya Es Muy Tarde
48   Gloomy Sunday (with Teddy Wilson & His Orchest...
134                                            Changes
141                                Big Girls Don't Cry
147                         Papa's Got A Brand New Bag
154                                       Boogie Shoes
158                  Suicidal Thoughts - 2005 Remaster
159                               You Made Me Love You

                                      artist_names  valence  energy  \
6                                  ['The Killers']   0.2360  0.9110
27   ['Louis Armstrong & His Savoy Ballroom Five']   0.4380  0.1990
31                                 ['Los Panchos']   0.7820  0.3140
48              ['Billie Holiday', 'Teddy Wilson']   0.2230  0.0433
134                             ['2Pac', 'Talent']   0.3160  0.6570
141           ['Frankie Valli & The Four Seasons']   0.8430  0.8400
147                                ['James Brown']   0.9250  0.5410
154                     ['KC & The Sunshine Band']   0.9630  0.8390
158                       ['The Notorious B.I.G.']   0.0788  0.5050
159                                ['Harry James']   0.2330  0.1900

                                            album_name
6                                             Hot Fuss
27          Volume IV - Louis Armstrong And Earl Hines
31                                        Personalidad
48   Lady Day: The Complete Billie Holiday On Colum...
134                                   The Best of 2Pac
141                           Sherry and 11 Other Hits
147                                          Star Time
154  Saturday Night Fever (The Original Movie Sound...
158         Ready to Die (The Remaster; 2015 Remaster)
159                              Best Of The Big Bands

In [23]:
deduped_df['release_date'] = pd.to_datetime(deduped_df['release_date'], errors='coerce')

# Sort to keep most recent
deduped_sorted = deduped_df.sort_values(by='release_date', ascending=False)

# Drop duplicates keeping most recent
refined_df = deduped_sorted.drop_duplicates(subset=['track_name', 'artist_names'], keep='first')
print(f"Refined dataset shape: {refined_df.shape}")

Refined dataset shape: (33234, 11)

C:\Users\mishr\AppData\Local\Temp\ipykernel_3064\3497222924.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  deduped_df['release_date'] = pd.to_datetime(deduped_df['release_date'], errors='coerce')

In [36]:
refined_df

,track_id,track_name,artist_names,genres,valence,danceability,energy,mood,album_name,release_date,album_cover_640x640
8439,1LmN9SSHISbtp9LoaR5ZVJ,Payphone,"['Maroon 5', 'Wiz Khalifa']","rap, southern hip hop, pop, trap, pop rap, pit...",0.523,0.739,0.7560,Neutral,Overexposed,2021-06-20,https://i.scdn.co/image/ab67616d0000b2733119f4...
33329,7IfdPERQJutZVYZemjrPBG,Peligrosa,"['J Balvin', 'Wisin & Yandel']","trap latino, electro latino, reggaeton, reggae...",0.680,0.769,0.7590,Upbeat,DJ Home Office Vol. 1,2020-11-20,https://i.scdn.co/image/ab67616d0000b273beccbe...
11850,249gnXrbfmV8NG6jTEMSwD,Life Goes On,['BTS'],"pop, k-pop, k-pop boy group",0.450,0.566,0.7160,Neutral,BE,2020-11-20,https://i.scdn.co/image/ab67616d0000b2733deb4b...
30774,6d97KmrQGLdE6TVfGTW3PD,Mami,['J Balvin'],"reggaeton colombiano, urbano latino, trap lati...",0.924,0.727,0.7760,Upbeat,Playa Reggae,2020-11-20,https://i.scdn.co/image/ab67616d0000b273b1bd4d...
23319,4j9bUBWorNXVrmT2fppDgv,Safari,"['J Balvin', 'Pharrell Williams', 'BIA', 'Sky']","rap latina, trap latino, trap queen, pop, danc...",0.604,0.689,0.6750,Upbeat,Baila el dembow,2020-11-20,https://i.scdn.co/image/ab67616d0000b273c41c25...
...,...,...,...,...,...,...,...,...,...,...,...
35188,7zrxGPR1UVK2iSK793vLPl,Spanish Pipedream,['John Prine'],"folk, new americana, singer-songwriter, roots ...",0.854,0.671,0.4010,Upbeat,John Prine,NaT,https://i.scdn.co/image/ab67616d0000485103c6a7...
35193,7zto61V8ySp03Qi6X1LU2X,Tin Pan Alley (AKA Roughest Place in Town),['Stevie Ray Vaughan'],"classic rock, instrumental rock, blues, electr...",0.168,0.576,0.0968,Sad,Couldn't Stand The Weather (Legacy Edition),NaT,https://i.scdn.co/image/ab67616d0000b273eb72e9...
35194,7zty9mmmuqQsn8s4zDH4nk,メリッサ,['PornoGraffitti'],Unknown,0.799,0.538,0.9280,Upbeat,NaN,NaT,NaN
35196,7zwNt8YuTz0wXYJEW64jbF,Freak Scene,['Dinosaur Jr.'],"slacker rock, lo-fi, power pop, noise rock, al...",0.222,0.290,0.9390,Sad,NaN,NaT,NaN
35198,7zzbfi8fvHe6hm342GcNYl,Black-Throated Wind,['Bob Weir'],Unknown,0.669,0.533,0.5470,Upbeat,NaN,NaT,NaN

# REFINED  DATA

In [24]:
refined_df.to_csv('D:\\snap_tune_final\\snap_tune_project\\proceesed_songs\\processed_songs_refined.csv', index=False)
print("Refined dataset shape:", refined_df.shape)

Refined dataset shape: (33234, 11)

In [25]:
# Check for NaN columns
nan_columns = refined_df.columns[refined_df.isna().any()].tolist()

if nan_columns:
    print(" Columns with NaN values:", nan_columns)
    print("NaN count per column:")
    print(refined_df[nan_columns].isna().sum())
else:
    print(" No NaN values found in any column.")

 Columns with NaN values: ['album_name', 'release_date', 'album_cover_640x640']
NaN count per column:
album_name              5883
release_date           14554
album_cover_640x640     5883
dtype: int64

In [37]:
refined_df.loc[:, 'album_name'] = refined_df['album_name'].fillna('Unknown')
refined_df.loc[:, 'album_cover_640x640'] = refined_df['album_cover_640x640'].fillna('No Image Available')
refined_df.to_csv('D:\\snap_tune_final\\snap_tune_project\\proceesed_songs\\processed_songs_final_refined.csv', index=False)
print("Refined dataset saved with NaN values handled.")

Refined dataset saved with NaN values handled.

In [40]:
refined_df_final=pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\proceesed_songs\\processed_songs_final_refined.csv')

In [41]:
refined_df_final

,track_id,track_name,artist_names,genres,valence,danceability,energy,mood,album_name,release_date,album_cover_640x640
0,1LmN9SSHISbtp9LoaR5ZVJ,Payphone,"['Maroon 5', 'Wiz Khalifa']","pop, hip hop, pittsburgh rap, southern hip hop...",0.523,0.739,0.7560,Neutral,Overexposed,2021-06-20,https://i.scdn.co/image/ab67616d0000b2733119f4...
1,7IfdPERQJutZVYZemjrPBG,Peligrosa,"['J Balvin', 'Wisin & Yandel']","electro latino, urbano latino, reggaeton, regg...",0.680,0.769,0.7590,Upbeat,DJ Home Office Vol. 1,2020-11-20,https://i.scdn.co/image/ab67616d0000b273beccbe...
2,249gnXrbfmV8NG6jTEMSwD,Life Goes On,['BTS'],"pop, k-pop, k-pop boy group",0.450,0.566,0.7160,Neutral,BE,2020-11-20,https://i.scdn.co/image/ab67616d0000b2733deb4b...
3,6d97KmrQGLdE6TVfGTW3PD,Mami,['J Balvin'],"reggaeton, reggaeton colombiano, urbano latino...",0.924,0.727,0.7760,Upbeat,Playa Reggae,2020-11-20,https://i.scdn.co/image/ab67616d0000b273b1bd4d...
4,4j9bUBWorNXVrmT2fppDgv,Safari,"['J Balvin', 'Pharrell Williams', 'BIA', 'Sky']","trap queen, urbano latino, dance pop, reggaeto...",0.604,0.689,0.6750,Upbeat,Baila el dembow,2020-11-20,https://i.scdn.co/image/ab67616d0000b273c41c25...
...,...,...,...,...,...,...,...,...,...,...,...
33229,7zrxGPR1UVK2iSK793vLPl,Spanish Pipedream,['John Prine'],"folk, singer-songwriter, roots rock, new ameri...",0.854,0.671,0.4010,Upbeat,John Prine,NaN,https://i.scdn.co/image/ab67616d0000485103c6a7...
33230,7zto61V8ySp03Qi6X1LU2X,Tin Pan Alley (AKA Roughest Place in Town),['Stevie Ray Vaughan'],"instrumental rock, blues rock, hard rock, clas...",0.168,0.576,0.0968,Sad,Couldn't Stand The Weather (Legacy Edition),NaN,https://i.scdn.co/image/ab67616d0000b273eb72e9...
33231,7zty9mmmuqQsn8s4zDH4nk,メリッサ,['PornoGraffitti'],Unknown,0.799,0.538,0.9280,Upbeat,Unknown,NaN,No Image Available
33232,7zwNt8YuTz0wXYJEW64jbF,Freak Scene,['Dinosaur Jr.'],"permanent wave, alternative rock, noise pop, l...",0.222,0.290,0.9390,Sad,Unknown,NaN,No Image Available
33233,7zzbfi8fvHe6hm342GcNYl,Black-Throated Wind,['Bob Weir'],Unknown,0.669,0.533,0.5470,Upbeat,Unknown,NaN,No Image Available

# check for few duplicates rows

In [26]:


duplicate_rows = refined_df[refined_df.duplicated()]
print("Duplicate rows (keeping the first occurrence as unique):")
print(duplicate_rows)

Duplicate rows (keeping the first occurrence as unique):
Empty DataFrame
Columns: [track_id, track_name, artist_names, genres, valence, danceability, energy, mood, album_name, release_date, album_cover_640x640]
Index: []

In [27]:
refined_df.columns  #check for the columns in the dataframe

Index(['track_id', 'track_name', 'artist_names', 'genres', 'valence',
       'danceability', 'energy', 'mood', 'album_name', 'release_date',
       'album_cover_640x640'],
      dtype='object')

In [42]:
refined_df['mood'].unique()  #check for the unique values

array(['Neutral', 'Upbeat', 'Sad'], dtype=object)

In [43]:
refined_df.isnull().sum()  #chec for null columns

track_id                   0
track_name                 0
artist_names               0
genres                     0
valence                    0
danceability               0
energy                     0
mood                       0
album_name                 0
release_date           14554
album_cover_640x640        0
dtype: int64

In [44]:
print(refined_df['genres'].head(10)) #print first 10 generes
print(refined_df['artist_names'].head(10)) #print first 10 artists names

14108    pop, hip hop, pittsburgh rap, southern hip hop...
53695    electro latino, urbano latino, reggaeton, regg...
19842                          pop, k-pop, k-pop boy group
49756    reggaeton, reggaeton colombiano, urbano latino...
38315    trap queen, urbano latino, dance pop, reggaeto...
34450    reggaeton, reggaeton colombiano, urbano latino...
30808    latin hip hop, urbano latino, reggaeton, regga...
49217    reggaeton, reggaeton colombiano, urbano latino...
49851    urbano latino, r&b, reggaeton, reggaeton colom...
36238    reggaeton, reggaeton colombiano, urbano latino...
Name: genres, dtype: object
14108                        ['Maroon 5', 'Wiz Khalifa']
53695                     ['J Balvin', 'Wisin & Yandel']
19842                                            ['BTS']
49756                                       ['J Balvin']
38315    ['J Balvin', 'Pharrell Williams', 'BIA', 'Sky']
34450                                       ['J Balvin']
30808                       ['J Balvin', 'Daddy Yankee']
49217                                       ['J Balvin']
49851           ['J Balvin', 'Willy William', 'Beyoncé']
36238                                       ['J Balvin']
Name: artist_names, dtype: object

In [45]:
df_temp = deduped_df.copy()
df_temp['mood_encoded'] = df_temp['mood'].astype('category').cat.codes

print(df_temp.corr(numeric_only=True)['mood_encoded'].sort_values(ascending=False))

mood_encoded    1.000000
valence         0.574561
danceability    0.271144
energy          0.172178
Name: mood_encoded, dtype: float64

In [46]:
deduped_df['mood'].value_counts()   #check for the count of the values  OR count the unique values

mood
Upbeat     16264
Sad        10594
Neutral     8342
Name: count, dtype: int64

# MUSIC SENTIMENT DATA SETS

In [28]:
#load the data sets
music_sentiment_df=pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\datas\\music_sentiment_data-set\\music_sentiment_dataset.csv')

In [29]:
music_sentiment_df

,User_ID,User_Text,Sentiment_Label,Recommended_Song_ID,Song_Name,Artist,Genre,Tempo (BPM),Mood,Energy,Danceability
0,U1,Way ball purpose public experience recently re...,Sad,S1,Someone Like You,Adele,Pop,67,Melancholic,Low,Low
1,U2,Save officer two myself a.,Happy,S2,Happy,Pharrell Williams,Pop,160,Joyful,High,High
2,U3,Decade ahead everyone environment themselves a...,Relaxed,S3,Clair de Lune,Debussy,Classical,60,Soothing,Low,Low
3,U4,Best change letter citizen try ask quality pro...,Happy,S4,Happy,Pharrell Williams,Pop,160,Joyful,High,High
4,U5,Worker player chance kind actually.,Happy,S5,Happy,Pharrell Williams,Pop,160,Joyful,High,High
...,...,...,...,...,...,...,...,...,...,...,...
995,U996,Where carry sit argue through street.,Relaxed,S996,Clair de Lune,Debussy,Classical,60,Soothing,Low,Low
996,U997,Agreement state up hope free manage outside.,Happy,S997,Happy,Pharrell Williams,Pop,160,Joyful,High,High
997,U998,Particular else challenge ball.,Relaxed,S998,Clair de Lune,Debussy,Classical,60,Soothing,Low,Low
998,U999,Much level someone.,Relaxed,S999,Weightless,Marconi Union,Ambient,50,Calm,Low,Low
999,U1000,Appear the two score.,Relaxed,S1000,Weightless,Marconi Union,Ambient,50,Calm,Low,Low

In [30]:
#MUSIC SENTIMENT DATASET
music_sentiment_df.shape

(1000, 11)

In [35]:
# Check for NaN columns
nan_columns = music_sentiment_df.columns[music_sentiment_df.isna().any()].tolist()

if nan_columns:
    print(" Columns with NaN values:", nan_columns)
    print("NaN count per column:")
    print(music_sentiment_df[nan_columns].isna().sum())
else:
    print(" No NaN values found in any column.")

 No NaN values found in any column.

In [31]:
music_sentiment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   User_ID              1000 non-null   object
 1   User_Text            1000 non-null   object
 2   Sentiment_Label      1000 non-null   object
 3   Recommended_Song_ID  1000 non-null   object
 4   Song_Name            1000 non-null   object
 5   Artist               1000 non-null   object
 6   Genre                1000 non-null   object
 7   Tempo (BPM)          1000 non-null   int64
 8   Mood                 1000 non-null   object
 9   Energy               1000 non-null   object
 10  Danceability         1000 non-null   object
dtypes: int64(1), object(10)
memory usage: 86.1+ KB

In [32]:
music_sentiment_df.columns

Index(['User_ID', 'User_Text', 'Sentiment_Label', 'Recommended_Song_ID',
       'Song_Name', 'Artist', 'Genre', 'Tempo (BPM)', 'Mood', 'Energy',
       'Danceability'],
      dtype='object')

In [46]:
repeated_rows = music_sentiment_df[music_sentiment_df.duplicated()]
print(f"Number of repeated rows: {len(repeated_rows)}")

Number of repeated rows: 0

In [33]:
music_sentiment_df.isnull().sum()  #check for null columns

User_ID                0
User_Text              0
Sentiment_Label        0
Recommended_Song_ID    0
Song_Name              0
Artist                 0
Genre                  0
Tempo (BPM)            0
Mood                   0
Energy                 0
Danceability           0
dtype: int64

# SPotify Milion sONGS Dat SETA

In [3]:
milion_songa_data=pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\datas\\spotify_milion_songs_datasets\\spotify\\spotify_millsongdata.csv')

In [4]:
milion_songa_data.shape

(57650, 4)

In [5]:
milion_songa_data.columns

Index(['artist', 'song', 'link', 'text'], dtype='object')

In [7]:
milion_songa_data.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [8]:
milion_songa_data['artist']

0                ABBA
1                ABBA
2                ABBA
3                ABBA
4                ABBA
             ...
57645    Ziggy Marley
57646    Ziggy Marley
57647            Zwan
57648            Zwan
57649            Zwan
Name: artist, Length: 57650, dtype: object

In [9]:
milion_songa_data['song']

0        Ahe's My Kind Of Girl
1             Andante, Andante
2               As Good As New
3                         Bang
4             Bang-A-Boomerang
                 ...
57645            Good Old Days
57646            Hand To Mouth
57647             Come With Me
57648                   Desire
57649                Heartsong
Name: song, Length: 57650, dtype: object

# Merging of music sentiment and refined data sets

In [47]:


# Load the datasets
refined_df = pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\proceesed_songs\\processed_songs_final_refined.csv')  # Your refined dataset
music_sentiment_df = pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\datas\\music_sentiment_data-set\\music_sentiment_dataset.csv')  # Music Sentiment Dataset

# Standardize column names in Music Sentiment Dataset
music_sentiment_df.rename(columns={'Song_Name': 'track_name', 'Artist': 'artist_names'}, inplace=True)

# Merge with refined dataset on 'track_name' and 'artist_names'
merged_df = pd.merge(
    refined_df,
    music_sentiment_df[['track_name', 'artist_names', 'Sentiment_Label', 'Mood', 'Energy', 'Danceability']],
    on=['track_name', 'artist_names'],
    how='left'
)

# Check for duplicates based on 'track_id' (assuming it exists in refined_df)
duplicates = merged_df[merged_df.duplicated(subset=['track_id'], keep=False)]
print(f"Number of duplicate track_ids: {len(duplicates)}")

# Remove duplicates, keeping the first occurrence
if not duplicates.empty:
    merged_df = merged_df.drop_duplicates(subset='track_id', keep='first')

# Handle missing values
merged_df['Sentiment_Label'] = merged_df['Sentiment_Label'].fillna('Unknown')
merged_df['Mood'] = merged_df['Mood'].fillna('Unknown')
merged_df['Energy'] = merged_df['Energy'].fillna(0)
merged_df['Danceability'] = merged_df['Danceability'].fillna(0)

# Verify the result
print(f"Shape after merging Music Sentiment Dataset: {merged_df.shape}")
print(merged_df.head())

# Save the intermediate result
merged_df.to_csv('path_to_intermediate_merged_df.csv', index=False)
print("Intermediate merged dataset saved.")

Number of duplicate track_ids: 0
Shape after merging Music Sentiment Dataset: (33234, 15)
                 track_id    track_name  \
0  1LmN9SSHISbtp9LoaR5ZVJ      Payphone
1  7IfdPERQJutZVYZemjrPBG     Peligrosa
2  249gnXrbfmV8NG6jTEMSwD  Life Goes On
3  6d97KmrQGLdE6TVfGTW3PD          Mami
4  4j9bUBWorNXVrmT2fppDgv        Safari

                                      artist_names  \
0                      ['Maroon 5', 'Wiz Khalifa']
1                   ['J Balvin', 'Wisin & Yandel']
2                                          ['BTS']
3                                     ['J Balvin']
4  ['J Balvin', 'Pharrell Williams', 'BIA', 'Sky']

                                              genres  valence  danceability  \
0  pop, hip hop, pittsburgh rap, southern hip hop...    0.523         0.739
1  electro latino, urbano latino, reggaeton, regg...    0.680         0.769
2                        pop, k-pop, k-pop boy group    0.450         0.566
3  reggaeton, reggaeton colombiano, urbano latino...    0.924         0.727
4  trap queen, urbano latino, dance pop, reggaeto...    0.604         0.689

   energy     mood             album_name release_date  \
0   0.756  Neutral            Overexposed   2021-06-20
1   0.759   Upbeat  DJ Home Office Vol. 1   2020-11-20
2   0.716  Neutral                     BE   2020-11-20
3   0.776   Upbeat           Playa Reggae   2020-11-20
4   0.675   Upbeat        Baila el dembow   2020-11-20

                                 album_cover_640x640 Sentiment_Label     Mood  \
0  https://i.scdn.co/image/ab67616d0000b2733119f4...         Unknown  Unknown
1  https://i.scdn.co/image/ab67616d0000b273beccbe...         Unknown  Unknown
2  https://i.scdn.co/image/ab67616d0000b2733deb4b...         Unknown  Unknown
3  https://i.scdn.co/image/ab67616d0000b273b1bd4d...         Unknown  Unknown
4  https://i.scdn.co/image/ab67616d0000b273c41c25...         Unknown  Unknown

   Energy  Danceability
0       0             0
1       0             0
2       0             0
3       0             0
4       0             0

C:\Users\mishr\AppData\Local\Temp\ipykernel_3064\2140026169.py:27: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  merged_df['Energy'] = merged_df['Energy'].fillna(0)
C:\Users\mishr\AppData\Local\Temp\ipykernel_3064\2140026169.py:28: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  merged_df['Danceability'] = merged_df['Danceability'].fillna(0)

Intermediate merged dataset saved.

In [48]:
intermediate_merge_data=pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\proceesed_songs\\path_to_intermediate_merged_df.csv')

In [49]:
intermediate_merge_data

,track_id,track_name,artist_names,genres,valence,danceability,energy,mood,album_name,release_date,album_cover_640x640,Sentiment_Label,Mood,Energy,Danceability
0,1LmN9SSHISbtp9LoaR5ZVJ,Payphone,"['Maroon 5', 'Wiz Khalifa']","pop, hip hop, pittsburgh rap, southern hip hop...",0.523,0.739,0.7560,Neutral,Overexposed,2021-06-20,https://i.scdn.co/image/ab67616d0000b2733119f4...,Unknown,Unknown,0,0
1,7IfdPERQJutZVYZemjrPBG,Peligrosa,"['J Balvin', 'Wisin & Yandel']","electro latino, urbano latino, reggaeton, regg...",0.680,0.769,0.7590,Upbeat,DJ Home Office Vol. 1,2020-11-20,https://i.scdn.co/image/ab67616d0000b273beccbe...,Unknown,Unknown,0,0
2,249gnXrbfmV8NG6jTEMSwD,Life Goes On,['BTS'],"pop, k-pop, k-pop boy group",0.450,0.566,0.7160,Neutral,BE,2020-11-20,https://i.scdn.co/image/ab67616d0000b2733deb4b...,Unknown,Unknown,0,0
3,6d97KmrQGLdE6TVfGTW3PD,Mami,['J Balvin'],"reggaeton, reggaeton colombiano, urbano latino...",0.924,0.727,0.7760,Upbeat,Playa Reggae,2020-11-20,https://i.scdn.co/image/ab67616d0000b273b1bd4d...,Unknown,Unknown,0,0
4,4j9bUBWorNXVrmT2fppDgv,Safari,"['J Balvin', 'Pharrell Williams', 'BIA', 'Sky']","trap queen, urbano latino, dance pop, reggaeto...",0.604,0.689,0.6750,Upbeat,Baila el dembow,2020-11-20,https://i.scdn.co/image/ab67616d0000b273c41c25...,Unknown,Unknown,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33229,7zrxGPR1UVK2iSK793vLPl,Spanish Pipedream,['John Prine'],"folk, singer-songwriter, roots rock, new ameri...",0.854,0.671,0.4010,Upbeat,John Prine,NaN,https://i.scdn.co/image/ab67616d0000485103c6a7...,Unknown,Unknown,0,0
33230,7zto61V8ySp03Qi6X1LU2X,Tin Pan Alley (AKA Roughest Place in Town),['Stevie Ray Vaughan'],"instrumental rock, blues rock, hard rock, clas...",0.168,0.576,0.0968,Sad,Couldn't Stand The Weather (Legacy Edition),NaN,https://i.scdn.co/image/ab67616d0000b273eb72e9...,Unknown,Unknown,0,0
33231,7zty9mmmuqQsn8s4zDH4nk,メリッサ,['PornoGraffitti'],Unknown,0.799,0.538,0.9280,Upbeat,Unknown,NaN,No Image Available,Unknown,Unknown,0,0
33232,7zwNt8YuTz0wXYJEW64jbF,Freak Scene,['Dinosaur Jr.'],"permanent wave, alternative rock, noise pop, l...",0.222,0.290,0.9390,Sad,Unknown,NaN,No Image Available,Unknown,Unknown,0,0
33233,7zzbfi8fvHe6hm342GcNYl,Black-Throated Wind,['Bob Weir'],Unknown,0.669,0.533,0.5470,Upbeat,Unknown,NaN,No Image Available,Unknown,Unknown,0,0

In [71]:
import pandas as pd

# Define dtypes for columns to avoid DtypeWarning
dtypes = {
    'track_id': 'str',
    'track_name': 'str',
    'artist_names': 'str',
    'genres': 'str',
    'valence': 'float',
    'danceability': 'float',
    'energy': 'float',
    'mood': 'str',
    'album_name': 'str',
    'release_date': 'str',  # Handle as string to avoid mixed type issues
    'album_cover_640x640': 'str',
    'Sentiment_Label': 'str',
    'Mood': 'str',
    'Energy': 'float',
    'Danceability': 'float',
    'text': 'str'
}

# Load the final merged dataset with specified dtypes
df = pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\path_to_final_merged_df.csv', dtype=dtypes, low_memory=False)

# Check column 9 to confirm
print(f"Column at index 9: {df.columns[9]}")

# Convert release_date to datetime, handling errors
df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')

# Standardize mood labels
mood_mapping = {
    'Upbeat': 'Upbeat',
    'Positive': 'Upbeat',
    'Happy': 'Upbeat',
    'Sad': 'Sad',
    'Negative': 'Sad',
    'Neutral': 'Neutral',
    'Unknown': 'Neutral'
}
df['mood'] = df['mood'].combine_first(df['Sentiment_Label']).map(mood_mapping).fillna('Neutral')

# Ensure no NaN values in critical columns
df['genres'] = df['genres'].fillna('Unknown')
df['track_name'] = df['track_name'].fillna('Unknown')
df['artist_names'] = df['artist_names'].fillna('Unknown')
df['album_name'] = df['album_name'].fillna('Unknown')
df['album_cover_640x640'] = df['album_cover_640x640'].fillna('No Image Available')
df['text'] = df['text'].fillna('No Lyrics Available')

# Extract unique genres for UI dropdown
unique_genres = sorted(df['genres'].str.split(', ').explode().unique())

# Save the cleaned dataset
df.to_csv('D:\\snap_tune_final\\snap_tune_project\\proceesed_songs\\cleaned_final_df.csv', index=False)
print(f"Cleaned dataset shape: {df.shape}")
print(f"Unique genres: {unique_genres}")

Column at index 9: release_date
Cleaned dataset shape: (33234, 16)

# MERGING WITH SPOTIFY MILIONS DATA SETS

In [64]:
import pandas as pd

# Load the intermediate merged dataset and Spotify dataset
intermediate_df = pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\proceesed_songs\\path_to_intermediate_merged_df.csv')  # INTERMEDIATE
spotify_df = pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\datas\\spotify_milion_songs_datasets\\spotify\\spotify_millsongdata.csv')  # Spotify Million Songs Dataset

# Standardize column names in Spotify dataset
spotify_df.rename(columns={'song': 'track_name', 'artist': 'artist_names'}, inplace=True)

# Merge with intermediate dataset on 'track_name' and 'artist_names'
final_merged_df = pd.merge(
    intermediate_df,
    spotify_df[['track_name', 'artist_names', 'text']],
    on=['track_name', 'artist_names'],
    how='left'
)

# Handle missing lyrics
final_merged_df['text'] = final_merged_df['text'].fillna('No Lyrics Available')

# Verify the result
print(f"Shape after merging Spotify Dataset: {final_merged_df.shape}")
print(final_merged_df.head())

# Save the final merged dataset
final_merged_df.to_csv('path_to_final_merged_df.csv', index=False)
print("Final merged dataset saved.")

Shape after merging Spotify Dataset: (33234, 16)
                 track_id    track_name  \
0  1LmN9SSHISbtp9LoaR5ZVJ      Payphone
1  7IfdPERQJutZVYZemjrPBG     Peligrosa
2  249gnXrbfmV8NG6jTEMSwD  Life Goes On
3  6d97KmrQGLdE6TVfGTW3PD          Mami
4  4j9bUBWorNXVrmT2fppDgv        Safari

                                      artist_names  \
0                      ['Maroon 5', 'Wiz Khalifa']
1                   ['J Balvin', 'Wisin & Yandel']
2                                          ['BTS']
3                                     ['J Balvin']
4  ['J Balvin', 'Pharrell Williams', 'BIA', 'Sky']

                                              genres  valence  danceability  \
0  pop, hip hop, pittsburgh rap, southern hip hop...    0.523         0.739
1  electro latino, urbano latino, reggaeton, regg...    0.680         0.769
2                        pop, k-pop, k-pop boy group    0.450         0.566
3  reggaeton, reggaeton colombiano, urbano latino...    0.924         0.727
4  trap queen, urbano latino, dance pop, reggaeto...    0.604         0.689

   energy     mood             album_name release_date  \
0   0.756  Neutral            Overexposed   2021-06-20
1   0.759   Upbeat  DJ Home Office Vol. 1   2020-11-20
2   0.716  Neutral                     BE   2020-11-20
3   0.776   Upbeat           Playa Reggae   2020-11-20
4   0.675   Upbeat        Baila el dembow   2020-11-20

                                 album_cover_640x640 Sentiment_Label     Mood  \
0  https://i.scdn.co/image/ab67616d0000b2733119f4...         Unknown  Unknown
1  https://i.scdn.co/image/ab67616d0000b273beccbe...         Unknown  Unknown
2  https://i.scdn.co/image/ab67616d0000b2733deb4b...         Unknown  Unknown
3  https://i.scdn.co/image/ab67616d0000b273b1bd4d...         Unknown  Unknown
4  https://i.scdn.co/image/ab67616d0000b273c41c25...         Unknown  Unknown

   Energy  Danceability                 text
0       0             0  No Lyrics Available
1       0             0  No Lyrics Available
2       0             0  No Lyrics Available
3       0             0  No Lyrics Available
4       0             0  No Lyrics Available
Final merged dataset saved.

In [66]:
final_merged_=pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\path_to_final_merged_df.csv')

C:\Users\mishr\AppData\Local\Temp\ipykernel_3064\2114964264.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  final_merged_=pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\path_to_final_merged_df.csv')

In [54]:
final_merged_df

,track_id,track_name,artist_names,genres,valence,danceability,energy,mood,album_name,release_date,album_cover_640x640,Sentiment_Label,Mood,Energy,Danceability,text
0,1LmN9SSHISbtp9LoaR5ZVJ,Payphone,"['Maroon 5', 'Wiz Khalifa']","pop, hip hop, pittsburgh rap, southern hip hop...",0.523,0.739,0.7560,Neutral,Overexposed,2021-06-20,https://i.scdn.co/image/ab67616d0000b2733119f4...,Unknown,Unknown,0,0,No Lyrics Available
1,7IfdPERQJutZVYZemjrPBG,Peligrosa,"['J Balvin', 'Wisin & Yandel']","electro latino, urbano latino, reggaeton, regg...",0.680,0.769,0.7590,Upbeat,DJ Home Office Vol. 1,2020-11-20,https://i.scdn.co/image/ab67616d0000b273beccbe...,Unknown,Unknown,0,0,No Lyrics Available
2,249gnXrbfmV8NG6jTEMSwD,Life Goes On,['BTS'],"pop, k-pop, k-pop boy group",0.450,0.566,0.7160,Neutral,BE,2020-11-20,https://i.scdn.co/image/ab67616d0000b2733deb4b...,Unknown,Unknown,0,0,No Lyrics Available
3,6d97KmrQGLdE6TVfGTW3PD,Mami,['J Balvin'],"reggaeton, reggaeton colombiano, urbano latino...",0.924,0.727,0.7760,Upbeat,Playa Reggae,2020-11-20,https://i.scdn.co/image/ab67616d0000b273b1bd4d...,Unknown,Unknown,0,0,No Lyrics Available
4,4j9bUBWorNXVrmT2fppDgv,Safari,"['J Balvin', 'Pharrell Williams', 'BIA', 'Sky']","trap queen, urbano latino, dance pop, reggaeto...",0.604,0.689,0.6750,Upbeat,Baila el dembow,2020-11-20,https://i.scdn.co/image/ab67616d0000b273c41c25...,Unknown,Unknown,0,0,No Lyrics Available
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33229,7zrxGPR1UVK2iSK793vLPl,Spanish Pipedream,['John Prine'],"folk, singer-songwriter, roots rock, new ameri...",0.854,0.671,0.4010,Upbeat,John Prine,NaN,https://i.scdn.co/image/ab67616d0000485103c6a7...,Unknown,Unknown,0,0,No Lyrics Available
33230,7zto61V8ySp03Qi6X1LU2X,Tin Pan Alley (AKA Roughest Place in Town),['Stevie Ray Vaughan'],"instrumental rock, blues rock, hard rock, clas...",0.168,0.576,0.0968,Sad,Couldn't Stand The Weather (Legacy Edition),NaN,https://i.scdn.co/image/ab67616d0000b273eb72e9...,Unknown,Unknown,0,0,No Lyrics Available
33231,7zty9mmmuqQsn8s4zDH4nk,メリッサ,['PornoGraffitti'],Unknown,0.799,0.538,0.9280,Upbeat,Unknown,NaN,No Image Available,Unknown,Unknown,0,0,No Lyrics Available
33232,7zwNt8YuTz0wXYJEW64jbF,Freak Scene,['Dinosaur Jr.'],"permanent wave, alternative rock, noise pop, l...",0.222,0.290,0.9390,Sad,Unknown,NaN,No Image Available,Unknown,Unknown,0,0,No Lyrics Available
33233,7zzbfi8fvHe6hm342GcNYl,Black-Throated Wind,['Bob Weir'],Unknown,0.669,0.533,0.5470,Upbeat,Unknown,NaN,No Image Available,Unknown,Unknown,0,0,No Lyrics Available

# CLEANED CSVS

In [76]:
cleaned_csv=pd.read_csv('D:\\snap_tune_final\\snap_tune_project\\proceesed_songs\\cleaned_final_df.csv' ,low_memory=False)

In [77]:
cleaned_csv

,track_id,track_name,artist_names,genres,valence,danceability,energy,mood,album_name,release_date,album_cover_640x640,Sentiment_Label,Mood,Energy,Danceability,text
0,1LmN9SSHISbtp9LoaR5ZVJ,Payphone,"['Maroon 5', 'Wiz Khalifa']","pop, hip hop, pittsburgh rap, southern hip hop...",0.523,0.739,0.7560,Neutral,Overexposed,2021-06-20,https://i.scdn.co/image/ab67616d0000b2733119f4...,Unknown,Unknown,0.0,0.0,No Lyrics Available
1,7IfdPERQJutZVYZemjrPBG,Peligrosa,"['J Balvin', 'Wisin & Yandel']","electro latino, urbano latino, reggaeton, regg...",0.680,0.769,0.7590,Upbeat,DJ Home Office Vol. 1,2020-11-20,https://i.scdn.co/image/ab67616d0000b273beccbe...,Unknown,Unknown,0.0,0.0,No Lyrics Available
2,249gnXrbfmV8NG6jTEMSwD,Life Goes On,['BTS'],"pop, k-pop, k-pop boy group",0.450,0.566,0.7160,Neutral,BE,2020-11-20,https://i.scdn.co/image/ab67616d0000b2733deb4b...,Unknown,Unknown,0.0,0.0,No Lyrics Available
3,6d97KmrQGLdE6TVfGTW3PD,Mami,['J Balvin'],"reggaeton, reggaeton colombiano, urbano latino...",0.924,0.727,0.7760,Upbeat,Playa Reggae,2020-11-20,https://i.scdn.co/image/ab67616d0000b273b1bd4d...,Unknown,Unknown,0.0,0.0,No Lyrics Available
4,4j9bUBWorNXVrmT2fppDgv,Safari,"['J Balvin', 'Pharrell Williams', 'BIA', 'Sky']","trap queen, urbano latino, dance pop, reggaeto...",0.604,0.689,0.6750,Upbeat,Baila el dembow,2020-11-20,https://i.scdn.co/image/ab67616d0000b273c41c25...,Unknown,Unknown,0.0,0.0,No Lyrics Available
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33229,7zrxGPR1UVK2iSK793vLPl,Spanish Pipedream,['John Prine'],"folk, singer-songwriter, roots rock, new ameri...",0.854,0.671,0.4010,Upbeat,John Prine,NaN,https://i.scdn.co/image/ab67616d0000485103c6a7...,Unknown,Unknown,0.0,0.0,No Lyrics Available
33230,7zto61V8ySp03Qi6X1LU2X,Tin Pan Alley (AKA Roughest Place in Town),['Stevie Ray Vaughan'],"instrumental rock, blues rock, hard rock, clas...",0.168,0.576,0.0968,Sad,Couldn't Stand The Weather (Legacy Edition),NaN,https://i.scdn.co/image/ab67616d0000b273eb72e9...,Unknown,Unknown,0.0,0.0,No Lyrics Available
33231,7zty9mmmuqQsn8s4zDH4nk,メリッサ,['PornoGraffitti'],Unknown,0.799,0.538,0.9280,Upbeat,Unknown,NaN,No Image Available,Unknown,Unknown,0.0,0.0,No Lyrics Available
33232,7zwNt8YuTz0wXYJEW64jbF,Freak Scene,['Dinosaur Jr.'],"permanent wave, alternative rock, noise pop, l...",0.222,0.290,0.9390,Sad,Unknown,NaN,No Image Available,Unknown,Unknown,0.0,0.0,No Lyrics Available
33233,7zzbfi8fvHe6hm342GcNYl,Black-Throated Wind,['Bob Weir'],Unknown,0.669,0.533,0.5470,Upbeat,Unknown,NaN,No Image Available,Unknown,Unknown,0.0,0.0,No Lyrics Available